### ISSUE TITLE
To-Do for BETA Release

### ISSUE THREAD

**Issue by LaxSlash** [LaxSlash/forcestyles#1]
- [x] Get "Anonymous User" selection working
- [x] Configure the language strings to use Plurals properly
- [ ] Preferred themes for users
- [ ] Verify unset is run where needed
- [ ] Change laxslash_forcestyles to laxslash_fstyles
- [ ] Fix improper styling in the ACP Panel
- [ ] Are founder checks really necessary?
- [ ] Include/Exclude options for the criteria
- [x] What's the point of having usernames intersect with groups again? Should this be an on/off thing?
- [ ] Errors verifications and testing needs to be performed
- [ ] Travis build tests
- [x] Get permission authentication working
- [x] Create a CHANGELOG
- [x] Fix typo for override style setting error
- [x] Add the logging entries
- [ ] Selections not staying defined after an error?
